import { cars, type Car, type InsertCar, type CarFilter } from "@shared/schema";

export interface IStorage {
  getCars(): Promise<Car[]>;
  getFilteredCars(filter: CarFilter): Promise<Car[]>;
}

export class MemStorage implements IStorage {
  private cars: Car[];

  constructor() {
    this.cars = [
      // Entry Level Hatchbacks
      {
        id: 1,
        name: "Alto K10",
        brand: "Maruti Suzuki",
        price: "599000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.marutisuzuki.com/alto-k10",
        hasAutoAC: false,
        hasADAS: false,
        hasKeylessEntry: false,
        hasParkingSensors: false,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 2,
        name: "Kwid",
        brand: "Renault",
        price: "649000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.renault.co.in/cars/kwid",
        hasAutoAC: false,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 3,
        name: "S-Presso",
        brand: "Maruti Suzuki",
        price: "589000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.marutisuzuki.com/spresso",
        hasAutoAC: false,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: false,
        hasBlindSpotMonitoring: false,
      },
      // Premium Hatchbacks
      {
        id: 4,
        name: "Baleno",
        brand: "Maruti Suzuki",
        price: "849000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.marutisuzuki.com/baleno",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 5,
        name: "i20",
        brand: "Hyundai",
        price: "899000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.hyundai.com/in/en/find-a-car/i20",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 6,
        name: "Altroz",
        brand: "Tata",
        price: "799000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://cars.tatamotors.com/cars/altroz",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      // Compact SUVs
      {
        id: 7,
        name: "Nexon",
        brand: "Tata",
        price: "1199000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://nexon.tatamotors.com/",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 8,
        name: "Venue",
        brand: "Hyundai",
        price: "1089000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.hyundai.com/in/en/find-a-car/venue",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 9,
        name: "Brezza",
        brand: "Maruti Suzuki",
        price: "1149000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.marutisuzuki.com/brezza",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      // Mid-size SUVs
      {
        id: 10,
        name: "Creta",
        brand: "Hyundai",
        price: "1699000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.hyundai.com/in/en/find-a-car/creta",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 11,
        name: "Seltos",
        brand: "Kia",
        price: "1589000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.kia.com/in/our-vehicles/seltos/showroom.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 12,
        name: "XUV700",
        brand: "Mahindra",
        price: "1399000",
        seatingCapacity: 7,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://auto.mahindra.com/suv/xuv700",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 13,
        name: "Taigun",
        brand: "Volkswagen",
        price: "1549000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.volkswagen.co.in/en/models/taigun.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      // Premium SUVs
      {
        id: 14,
        name: "Fortuner",
        brand: "Toyota",
        price: "3500000",
        seatingCapacity: 7,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.toyotabharat.com/showroom/fortuner/",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 15,
        name: "Meridian",
        brand: "Jeep",
        price: "3289000",
        seatingCapacity: 7,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.jeep-india.com/meridian.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      // Entry-level Sedans
      {
        id: 16,
        name: "Amaze",
        brand: "Honda",
        price: "789000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.hondacarindia.com/honda-amaze",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 17,
        name: "Dzire",
        brand: "Maruti Suzuki",
        price: "749000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.marutisuzuki.com/dzire",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      // Mid-size Sedans
      {
        id: 18,
        name: "City",
        brand: "Honda",
        price: "1589000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.hondacarindia.com/honda-city",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 19,
        name: "Verna",
        brand: "Hyundai",
        price: "1089000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.hyundai.com/in/en/find-a-car/verna",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      // Premium Sedans
      {
        id: 20,
        name: "Camry",
        brand: "Toyota",
        price: "4499000",
        seatingCapacity: 5,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.toyotabharat.com/showroom/camry/",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      //Luxury Vehicles
      {
        id: 21,
        name: "Fortuner",
        brand: "Toyota",
        price: "3500000",
        seatingCapacity: 7,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.toyotabharat.com/showroom/fortuner/",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 22,
        name: "Carnival",
        brand: "Kia",
        price: "3500000",
        seatingCapacity: 7,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://www.kia.com/in/our-vehicles/carnival/features.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 23,
        name: "Safari",
        brand: "Tata",
        price: "2159000",
        seatingCapacity: 7,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://safari.tatamotors.com/",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 24,
        name: "Thar",
        brand: "Mahindra",
        price: "1399000",
        seatingCapacity: 4,
        image: "https://images.unsplash.com/photo-1675467129033-a2e1b188ae5b",
        officialLink: "https://auto.mahindra.com/suv/thar",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      }
    ];
  }

  async getCars(): Promise<Car[]> {
    return this.cars;
  }

  async getFilteredCars(filter: CarFilter): Promise<Car[]> {
    return this.cars.filter((car) => {
      const carPrice = parseFloat(car.price);
      const priceMatch = carPrice >= filter.minPrice && carPrice <= filter.maxPrice;
      const seatingMatch = car.seatingCapacity === filter.seatingCapacity;

      const featureMatch = filter.features.every((feature) => {
        switch (feature) {
          case "autoAC": return car.hasAutoAC;
          case "adas": return car.hasADAS;
          case "keylessEntry": return car.hasKeylessEntry;
          case "parkingSensors": return car.hasParkingSensors;
          case "blindSpotMonitoring": return car.hasBlindSpotMonitoring;
          default: return true;
        }
      });

      return priceMatch && seatingMatch && featureMatch;
    });
  }
}

export const storage = new MemStorage();