import { cars, type Car, type InsertCar, type CarFilter } from "@shared/schema";

export interface IStorage {
  getCars(): Promise<Car[]>;
  getFilteredCars(filter: CarFilter): Promise<Car[]>;
}

export class MemStorage implements IStorage {
  private cars: Car[];

  constructor() {
    this.cars = [
      // Entry Level Hatchbacks
      {
        id: 1,
        name: "Alto K10",
        brand: "Maruti Suzuki",
        price: "599000",
        seatingCapacity: 5,
        image: "/cars/alto.jpg",
        officialLink: "https://www.marutisuzuki.com/alto-k10",
        hasAutoAC: false,
        hasADAS: false,
        hasKeylessEntry: false,
        hasParkingSensors: false,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 2,
        name: "Kwid",
        brand: "Renault",
        price: "649000",
        seatingCapacity: 5,
        image: "/cars/kwid.jpg",
        officialLink: "https://www.renault.co.in/cars/kwid",
        hasAutoAC: false,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 3,
        name: "S-Presso",
        brand: "Maruti Suzuki",
        price: "589000",
        seatingCapacity: 5,
        image: "/cars/S-Presso.jpg",
        officialLink: "https://www.marutisuzuki.com/spresso",
        hasAutoAC: false,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: false,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 4,
        name: "WagonR",
        brand: "Maruti Suzuki",
        price: "599000",
        seatingCapacity: 5,
        image: "/cars/WagonR.jpg",
        officialLink: "https://www.marutisuzuki.com/wagonr",
        hasAutoAC: false,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: false,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 5,
        name: "Celerio",
        brand: "Maruti Suzuki",
        price: "649000",
        seatingCapacity: 5,
        image: "/cars/Celerio.jpg",
        officialLink: "https://www.marutisuzuki.com/celerio",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 6,
        name: "Tiago",
        brand: "Tata",
        price: "689000",
        seatingCapacity: 5,
        image: "/cars/Tiago.jpg",
        officialLink: "https://cars.tatamotors.com/cars/tiago",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      // Premium Hatchbacks
      {
        id: 7,
        name: "Baleno",
        brand: "Maruti Suzuki",
        price: "849000",
        seatingCapacity: 5,
        image: "/cars/Baleno.jpg",
        officialLink: "https://www.marutisuzuki.com/baleno",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 8,
        name: "i20",
        brand: "Hyundai",
        price: "899000",
        seatingCapacity: 5,
        image: "/cars/i20.webp",
        officialLink: "https://www.hyundai.com/in/en/find-a-car/i20",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 9,
        name: "Altroz",
        brand: "Tata",
        price: "799000",
        seatingCapacity: 5,
        image: "/cars/Altroz.webp",
        officialLink: "https://cars.tatamotors.com/cars/altroz",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 10,
        name: "Glanza",
        brand: "Toyota",
        price: "849000",
        seatingCapacity: 5,
        image: "/cars/Glanza.webp",
        officialLink: "https://www.toyotabharat.com/showroom/glanza",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 11,
        name: "Polo",
        brand: "Volkswagen",
        price: "849000",
        seatingCapacity: 5,
        image: "/cars/Polo.webp",
        officialLink: "https://www.volkswagen.co.in/en/models/polo.html",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      // Compact SUVs
      {
        id: 12,
        name: "Nexon",
        brand: "Tata",
        price: "1199000",
        seatingCapacity: 5,
        image: "/cars/Nexon.jpg",
        officialLink: "https://nexon.tatamotors.com/",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 13,
        name: "Venue",
        brand: "Hyundai",
        price: "1089000",
        seatingCapacity: 5,
        image: "/cars/Venue.webp",
        officialLink: "https://www.hyundai.com/in/en/find-a-car/venue",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 14,
        name: "Brezza",
        brand: "Maruti Suzuki",
        price: "1149000",
        seatingCapacity: 5,
        image: "/cars/Brezza.jpg",
        officialLink: "https://www.marutisuzuki.com/brezza",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 15,
        name: "Sonet",
        brand: "Kia",
        price: "1089000",
        seatingCapacity: 5,
        image: "/cars/Sonet.jpg",
        officialLink: "https://www.kia.com/in/our-vehicles/sonet/showroom.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 16,
        name: "Magnite",
        brand: "Nissan",
        price: "999000",
        seatingCapacity: 5,
        image: "/cars/Magnite.jpg",
        officialLink: "https://www.nissan.in/vehicles/new/magnite.html",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 17,
        name: "XUV300",
        brand: "Mahindra",
        price: "1099000",
        seatingCapacity: 5,
        image: "/cars/XUV300.jpg",
        officialLink: "https://auto.mahindra.com/suv/xuv300",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      // Mid-size SUVs
      {
        id: 18,
        name: "Creta",
        brand: "Hyundai",
        price: "1699000",
        seatingCapacity: 5,
        image: "/cars/Creta.webp",
        officialLink: "https://www.hyundai.com/in/en/find-a-car/creta",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 19,
        name: "Seltos",
        brand: "Kia",
        price: "1589000",
        seatingCapacity: 5,
        image: "/cars/Seltos.jpg",
        officialLink: "https://www.kia.com/in/our-vehicles/seltos/showroom.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 20,
        name: "XUV700",
        brand: "Mahindra",
        price: "1399000",
        seatingCapacity: 7,
        image: "/cars/XUV700.jpg",
        officialLink: "https://auto.mahindra.com/suv/xuv700",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 21,
        name: "Taigun",
        brand: "Volkswagen",
        price: "1549000",
        seatingCapacity: 5,
        image: "/cars/Taigun.jpg",
        officialLink: "https://www.volkswagen.co.in/en/models/taigun.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 22,
        name: "Kushaq",
        brand: "Skoda",
        price: "1549000",
        seatingCapacity: 5,
        image: "/cars/Kushaq.webp",
        officialLink: "https://www.skoda-auto.co.in/models/kushaq",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 23,
        name: "Hyryder",
        brand: "Toyota",
        price: "1589000",
        seatingCapacity: 5,
        image: "/cars/Hyryder.webp",
        officialLink: "https://www.toyotabharat.com/showroom/hyryder",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      // Premium SUVs
      {
        id: 24,
        name: "Fortuner",
        brand: "Toyota",
        price: "3500000",
        seatingCapacity: 7,
        image: "/cars/Fortuner.webp",
        officialLink: "https://www.toyotabharat.com/showroom/fortuner/",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 25,
        name: "Meridian",
        brand: "Jeep",
        price: "3289000",
        seatingCapacity: 7,
        image: "/cars/Meridian.webp",
        officialLink: "https://www.jeep-india.com/meridian.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 26,
        name: "Compass",
        brand: "Jeep",
        price: "2099000",
        seatingCapacity: 5,
        image: "/cars/Compass.jpg",
        officialLink: "https://www.jeep-india.com/compass.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      // Entry-level Sedans
      {
        id: 27,
        name: "Amaze",
        brand: "Honda",
        price: "789000",
        seatingCapacity: 5,
        image: "/cars/Amaze.jpg",
        officialLink: "https://www.hondacarindia.com/honda-amaze",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 28,
        name: "Dzire",
        brand: "Maruti Suzuki",
        price: "749000",
        seatingCapacity: 5,
        image: "/cars/Dzire.webp",
        officialLink: "https://www.marutisuzuki.com/dzire",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      {
        id: 29,
        name: "Aura",
        brand: "Hyundai",
        price: "729000",
        seatingCapacity: 5,
        image: "/cars/Aura.jpg",
        officialLink: "https://www.hyundai.com/in/en/find-a-car/aura",
        hasAutoAC: true,
        hasADAS: false,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: false,
      },
      // Mid-size Sedans
      {
        id: 30,
        name: "City",
        brand: "Honda",
        price: "1589000",
        seatingCapacity: 5,
        image: "/cars/City.webp",
        officialLink: "https://www.hondacarindia.com/honda-city",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 31,
        name: "Verna",
        brand: "Hyundai",
        price: "1089000",
        seatingCapacity: 5,
        image: "/cars/Verna.webp",
        officialLink: "https://www.hyundai.com/in/en/find-a-car/verna",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 32,
        name: "Slavia",
        brand: "Skoda",
        price: "1289000",
        seatingCapacity: 5,
        image: "/cars/Slavia.webp",
        officialLink: "https://www.skoda-auto.co.in/models/slavia",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 33,
        name: "Virtus",
        brand: "Volkswagen",
        price: "1249000",
        seatingCapacity: 5,
        image: "/cars/Virtus.webp",
        officialLink: "https://www.volkswagen.co.in/en/models/virtus.html",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      // Premium Sedans
      {
        id: 34,
        name: "Camry",
        brand: "Toyota",
        price: "4499000",
        seatingCapacity: 5,
        image: "/cars/Camry.webp",
        officialLink: "https://www.toyotabharat.com/showroom/camry/",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      },
      {
        id: 35,
        name: "Superb",
        brand: "Skoda",
        price: "3499000",
        seatingCapacity: 5,
        image: "/cars/Superb.jpg",
        officialLink: "https://www.skoda-auto.co.in/models/superb",
        hasAutoAC: true,
        hasADAS: true,
        hasKeylessEntry: true,
        hasParkingSensors: true,
        hasBlindSpotMonitoring: true,
      }
    ];
  }

  async getCars(): Promise<Car[]> {
    return this.cars;
  }

  async getFilteredCars(filter: CarFilter): Promise<Car[]> {
    return this.cars.filter((car) => {
      const carPrice = parseFloat(car.price);
      const priceMatch = carPrice >= filter.minPrice && carPrice <= filter.maxPrice;
      const seatingMatch = car.seatingCapacity === filter.seatingCapacity;

      const featureMatch = filter.features.every((feature) => {
        switch (feature) {
          case "autoAC": return car.hasAutoAC;
          case "adas": return car.hasADAS;
          case "keylessEntry": return car.hasKeylessEntry;
          case "parkingSensors": return car.hasParkingSensors;
          case "blindSpotMonitoring": return car.hasBlindSpotMonitoring;
          default: return true;
        }
      });

      return priceMatch && seatingMatch && featureMatch;
    });
  }
}

export const storage = new MemStorage();